// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.mbv.airtime2.integration;

public final class RpcProto {
  private RpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string service_name = 1;
    boolean hasServiceName();
    String getServiceName();
    
    // required string method_name = 2;
    boolean hasMethodName();
    String getMethodName();
    
    // required bytes request_proto = 3;
    boolean hasRequestProto();
    com.google.protobuf.ByteString getRequestProto();
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mbv.airtime2.integration.RpcProto.internal_static_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mbv.airtime2.integration.RpcProto.internal_static_Request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string service_name = 1;
    public static final int SERVICE_NAME_FIELD_NUMBER = 1;
    private java.lang.Object serviceName_;
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          serviceName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string method_name = 2;
    public static final int METHOD_NAME_FIELD_NUMBER = 2;
    private java.lang.Object methodName_;
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          methodName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bytes request_proto = 3;
    public static final int REQUEST_PROTO_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString requestProto_;
    public boolean hasRequestProto() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getRequestProto() {
      return requestProto_;
    }
    
    private void initFields() {
      serviceName_ = "";
      methodName_ = "";
      requestProto_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasServiceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestProto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, requestProto_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, requestProto_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mbv.airtime2.integration.RpcProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mbv.airtime2.integration.RpcProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mbv.airtime2.integration.RpcProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mbv.airtime2.integration.RpcProto.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mbv.airtime2.integration.RpcProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mbv.airtime2.integration.RpcProto.internal_static_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mbv.airtime2.integration.RpcProto.internal_static_Request_fieldAccessorTable;
      }
      
      // Construct using com.mbv.airtime2.integration.RpcProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        requestProto_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mbv.airtime2.integration.RpcProto.Request.getDescriptor();
      }
      
      public com.mbv.airtime2.integration.RpcProto.Request getDefaultInstanceForType() {
        return com.mbv.airtime2.integration.RpcProto.Request.getDefaultInstance();
      }
      
      public com.mbv.airtime2.integration.RpcProto.Request build() {
        com.mbv.airtime2.integration.RpcProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mbv.airtime2.integration.RpcProto.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mbv.airtime2.integration.RpcProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mbv.airtime2.integration.RpcProto.Request buildPartial() {
        com.mbv.airtime2.integration.RpcProto.Request result = new com.mbv.airtime2.integration.RpcProto.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestProto_ = requestProto_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mbv.airtime2.integration.RpcProto.Request) {
          return mergeFrom((com.mbv.airtime2.integration.RpcProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mbv.airtime2.integration.RpcProto.Request other) {
        if (other == com.mbv.airtime2.integration.RpcProto.Request.getDefaultInstance()) return this;
        if (other.hasServiceName()) {
          setServiceName(other.getServiceName());
        }
        if (other.hasMethodName()) {
          setMethodName(other.getMethodName());
        }
        if (other.hasRequestProto()) {
          setRequestProto(other.getRequestProto());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasServiceName()) {
          
          return false;
        }
        if (!hasMethodName()) {
          
          return false;
        }
        if (!hasRequestProto()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serviceName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              methodName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              requestProto_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string service_name = 1;
      private java.lang.Object serviceName_ = "";
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setServiceName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      void setServiceName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
      }
      
      // required string method_name = 2;
      private java.lang.Object methodName_ = "";
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMethodName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      void setMethodName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
      }
      
      // required bytes request_proto = 3;
      private com.google.protobuf.ByteString requestProto_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasRequestProto() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getRequestProto() {
        return requestProto_;
      }
      public Builder setRequestProto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestProto_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestProto() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestProto_ = getDefaultInstance().getRequestProto();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Request)
  }
  
  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes response_proto = 1;
    boolean hasResponseProto();
    com.google.protobuf.ByteString getResponseProto();
    
    // optional string error = 2;
    boolean hasError();
    String getError();
    
    // optional bool callback = 3 [default = false];
    boolean hasCallback();
    boolean getCallback();
    
    // optional .Response.ServerErrorReason error_reason = 4;
    boolean hasErrorReason();
    com.mbv.airtime2.integration.RpcProto.Response.ServerErrorReason getErrorReason();
  }
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(Builder builder) {
      super(builder);
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mbv.airtime2.integration.RpcProto.internal_static_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mbv.airtime2.integration.RpcProto.internal_static_Response_fieldAccessorTable;
    }
    
    public enum ServerErrorReason
        implements com.google.protobuf.ProtocolMessageEnum {
      BAD_REQUEST_DATA(0, 0),
      BAD_REQUEST_PROTO(1, 1),
      SERVICE_NOT_FOUND(2, 2),
      METHOD_NOT_FOUND(3, 3),
      RPC_ERROR(4, 4),
      RPC_FAILED(5, 5),
      ;
      
      public static final int BAD_REQUEST_DATA_VALUE = 0;
      public static final int BAD_REQUEST_PROTO_VALUE = 1;
      public static final int SERVICE_NOT_FOUND_VALUE = 2;
      public static final int METHOD_NOT_FOUND_VALUE = 3;
      public static final int RPC_ERROR_VALUE = 4;
      public static final int RPC_FAILED_VALUE = 5;
      
      
      public final int getNumber() { return value; }
      
      public static ServerErrorReason valueOf(int value) {
        switch (value) {
          case 0: return BAD_REQUEST_DATA;
          case 1: return BAD_REQUEST_PROTO;
          case 2: return SERVICE_NOT_FOUND;
          case 3: return METHOD_NOT_FOUND;
          case 4: return RPC_ERROR;
          case 5: return RPC_FAILED;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ServerErrorReason>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ServerErrorReason>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ServerErrorReason>() {
              public ServerErrorReason findValueByNumber(int number) {
                return ServerErrorReason.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mbv.airtime2.integration.RpcProto.Response.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final ServerErrorReason[] VALUES = {
        BAD_REQUEST_DATA, BAD_REQUEST_PROTO, SERVICE_NOT_FOUND, METHOD_NOT_FOUND, RPC_ERROR, RPC_FAILED, 
      };
      
      public static ServerErrorReason valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private ServerErrorReason(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:Response.ServerErrorReason)
    }
    
    private int bitField0_;
    // optional bytes response_proto = 1;
    public static final int RESPONSE_PROTO_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString responseProto_;
    public boolean hasResponseProto() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getResponseProto() {
      return responseProto_;
    }
    
    // optional string error = 2;
    public static final int ERROR_FIELD_NUMBER = 2;
    private java.lang.Object error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          error_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool callback = 3 [default = false];
    public static final int CALLBACK_FIELD_NUMBER = 3;
    private boolean callback_;
    public boolean hasCallback() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getCallback() {
      return callback_;
    }
    
    // optional .Response.ServerErrorReason error_reason = 4;
    public static final int ERROR_REASON_FIELD_NUMBER = 4;
    private com.mbv.airtime2.integration.RpcProto.Response.ServerErrorReason errorReason_;
    public boolean hasErrorReason() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.mbv.airtime2.integration.RpcProto.Response.ServerErrorReason getErrorReason() {
      return errorReason_;
    }
    
    private void initFields() {
      responseProto_ = com.google.protobuf.ByteString.EMPTY;
      error_ = "";
      callback_ = false;
      errorReason_ = com.mbv.airtime2.integration.RpcProto.Response.ServerErrorReason.BAD_REQUEST_DATA;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, responseProto_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrorBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, callback_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, errorReason_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, responseProto_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrorBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, callback_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, errorReason_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mbv.airtime2.integration.RpcProto.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mbv.airtime2.integration.RpcProto.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mbv.airtime2.integration.RpcProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mbv.airtime2.integration.RpcProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mbv.airtime2.integration.RpcProto.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mbv.airtime2.integration.RpcProto.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mbv.airtime2.integration.RpcProto.internal_static_Response_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mbv.airtime2.integration.RpcProto.internal_static_Response_fieldAccessorTable;
      }
      
      // Construct using com.mbv.airtime2.integration.RpcProto.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        responseProto_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        callback_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        errorReason_ = com.mbv.airtime2.integration.RpcProto.Response.ServerErrorReason.BAD_REQUEST_DATA;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mbv.airtime2.integration.RpcProto.Response.getDescriptor();
      }
      
      public com.mbv.airtime2.integration.RpcProto.Response getDefaultInstanceForType() {
        return com.mbv.airtime2.integration.RpcProto.Response.getDefaultInstance();
      }
      
      public com.mbv.airtime2.integration.RpcProto.Response build() {
        com.mbv.airtime2.integration.RpcProto.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mbv.airtime2.integration.RpcProto.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mbv.airtime2.integration.RpcProto.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mbv.airtime2.integration.RpcProto.Response buildPartial() {
        com.mbv.airtime2.integration.RpcProto.Response result = new com.mbv.airtime2.integration.RpcProto.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.responseProto_ = responseProto_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.callback_ = callback_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.errorReason_ = errorReason_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mbv.airtime2.integration.RpcProto.Response) {
          return mergeFrom((com.mbv.airtime2.integration.RpcProto.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mbv.airtime2.integration.RpcProto.Response other) {
        if (other == com.mbv.airtime2.integration.RpcProto.Response.getDefaultInstance()) return this;
        if (other.hasResponseProto()) {
          setResponseProto(other.getResponseProto());
        }
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasCallback()) {
          setCallback(other.getCallback());
        }
        if (other.hasErrorReason()) {
          setErrorReason(other.getErrorReason());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              responseProto_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              error_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              callback_ = input.readBool();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.mbv.airtime2.integration.RpcProto.Response.ServerErrorReason value = com.mbv.airtime2.integration.RpcProto.Response.ServerErrorReason.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                errorReason_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes response_proto = 1;
      private com.google.protobuf.ByteString responseProto_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasResponseProto() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getResponseProto() {
        return responseProto_;
      }
      public Builder setResponseProto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        responseProto_ = value;
        onChanged();
        return this;
      }
      public Builder clearResponseProto() {
        bitField0_ = (bitField0_ & ~0x00000001);
        responseProto_ = getDefaultInstance().getResponseProto();
        onChanged();
        return this;
      }
      
      // optional string error = 2;
      private java.lang.Object error_ = "";
      public boolean hasError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setError(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        error_ = value;
        onChanged();
        return this;
      }
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      void setError(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        error_ = value;
        onChanged();
      }
      
      // optional bool callback = 3 [default = false];
      private boolean callback_ ;
      public boolean hasCallback() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getCallback() {
        return callback_;
      }
      public Builder setCallback(boolean value) {
        bitField0_ |= 0x00000004;
        callback_ = value;
        onChanged();
        return this;
      }
      public Builder clearCallback() {
        bitField0_ = (bitField0_ & ~0x00000004);
        callback_ = false;
        onChanged();
        return this;
      }
      
      // optional .Response.ServerErrorReason error_reason = 4;
      private com.mbv.airtime2.integration.RpcProto.Response.ServerErrorReason errorReason_ = com.mbv.airtime2.integration.RpcProto.Response.ServerErrorReason.BAD_REQUEST_DATA;
      public boolean hasErrorReason() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.mbv.airtime2.integration.RpcProto.Response.ServerErrorReason getErrorReason() {
        return errorReason_;
      }
      public Builder setErrorReason(com.mbv.airtime2.integration.RpcProto.Response.ServerErrorReason value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        errorReason_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorReason() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errorReason_ = com.mbv.airtime2.integration.RpcProto.Response.ServerErrorReason.BAD_REQUEST_DATA;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Response)
    }
    
    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Response)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\"K\n\007Request\022\024\n\014service_name\030\001" +
      " \002(\t\022\023\n\013method_name\030\002 \002(\t\022\025\n\rrequest_pro" +
      "to\030\003 \002(\014\"\214\002\n\010Response\022\026\n\016response_proto\030" +
      "\001 \001(\014\022\r\n\005error\030\002 \001(\t\022\027\n\010callback\030\003 \001(\010:\005" +
      "false\0221\n\014error_reason\030\004 \001(\0162\033.Response.S" +
      "erverErrorReason\"\214\001\n\021ServerErrorReason\022\024" +
      "\n\020BAD_REQUEST_DATA\020\000\022\025\n\021BAD_REQUEST_PROT" +
      "O\020\001\022\025\n\021SERVICE_NOT_FOUND\020\002\022\024\n\020METHOD_NOT" +
      "_FOUND\020\003\022\r\n\tRPC_ERROR\020\004\022\016\n\nRPC_FAILED\020\005B" +
      "*\n\034com.mbv.airtime2.integrationB\010RpcProt",
      "oH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Request_descriptor,
              new java.lang.String[] { "ServiceName", "MethodName", "RequestProto", },
              com.mbv.airtime2.integration.RpcProto.Request.class,
              com.mbv.airtime2.integration.RpcProto.Request.Builder.class);
          internal_static_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Response_descriptor,
              new java.lang.String[] { "ResponseProto", "Error", "Callback", "ErrorReason", },
              com.mbv.airtime2.integration.RpcProto.Response.class,
              com.mbv.airtime2.integration.RpcProto.Response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
